### ISSUE TITLE
Create a Scroll to top button

### ISSUE THREAD

**Issue by ashuvssut** [EnigmaVSSUT/EnigmaCMS-FrontEnd#32]
**Its icon** Must look like the image given below.
![image](https://user-images.githubusercontent.com/60546840/110222558-fc174400-7e87-11eb-98f8-05ef49f84e93.png)

Deliverables:
1. Make the button as a **separate React component** and give it that scroll to top functionality
2. This is a dark themed website So design the button to suit the theme
3. It must be a **material-ui IconButton** component

Remember on thing, to make the button appear only when user has scrolled down more the 400px (i.e `window.pageYOffset > 400`)

Use arrow icon from `@material-ui/icons`

**Comment by vmk8826** [comment]
i have created the code
am generating pull request so please check

**Comment by ashuvssut** [comment]
Yeah sure @vmk8826! I ll check it out!

**Comment by vmk8826** [comment]
is it good enough?

**Comment by ashuvssut** [comment]
Feel free to drop you comments regarding your contribution in your PR.😊
