### ISSUE TITLE
Event registration form

### ISSUE THREAD

**Issue by PKSingh0017** [EnigmaVSSUT/EnigmaCMS-FrontEnd#64]
Add an event registration form (preferably in a modal) to the "Register" button in [event detail](https://enigmavssut.com/events/3) page.

Here are the fields to be added in the form:
- event (ID of the perticular event)
- firstname
- lastname
- email
- year
- branch
   (dropdown with values you'll get by calling [this](https://api.vssut.ml/core/department-list/?type=academic) API url)
- gender
- whatsapp_no
- expectations

The values are ti be sent on [this](https://api.enigmavssut.com/events/register/) Api (POST method).

**Comment by IshitaSatpathy** [comment]
I will do it.

**Comment by ravindranag** [comment]
I have made this form bhaiya

**Comment by PKSingh0017** [comment]
> 

Yes, it just needs to added on the event detail page.

**Comment by PKSingh0017** [comment]
<img width="913" alt="Screenshot 2022-01-25 at 10 29 40 PM" src="https://user-images.githubusercontent.com/49274049/151023687-883ee060-ef12-47bb-8fd6-6b555c1f114d.png">

- [ ] Remove the field Event from the form, just add the id in payload.
- [ ] Add a cross button in the top right section of the modal.
- [ ] If possible change it to a side modal which open from the left side or right side.

**Comment by binayaksadangi** [comment]
Required changes has been done
