### ISSUE TITLE
Crate the public members detail page on the main site.

### ISSUE THREAD

**Issue by PKSingh0017** [EnigmaVSSUT/EnigmaCMS-FrontEnd#70]
- [x] Make the UX design.
- [x] Implement the UI.
- [x] Call the member detail API and make the integration.

**Comment by PKSingh0017** [comment]
Use (this)[https://api.enigmavssut.com/members/member-detail/abhipsa-swain/] endpoint
/members/member-detail/<slug>/

**Comment by binayaksadangi** [comment]
UX for the Profile Details Page
![ux1](https://user-images.githubusercontent.com/56728301/151939479-1921aa3b-dcdc-4f37-8c0a-546c7893cea4.jpeg)
![ux2](https://user-images.githubusercontent.com/56728301/151939498-f90cd3c1-1b42-4317-ace8-ffdd37cc8851.jpeg)

**Comment by binayaksadangi** [comment]
Issue resolved
