### ISSUE TITLE
Create three different sections in Events page

### ISSUE THREAD

**Issue by PKSingh0017** [EnigmaVSSUT/EnigmaCMS-FrontEnd#87]
Create three tabs in [events](https://enigmavssut.com/events) page.

**Comment by binayaksadangi** [comment]
1.Make the fontSize a little bit bigger of those tabs... and make all the tab colors green.

2.Dont use the custom Heading component ..that undeline is looking a little bit odd on the site. Use a Typography instead.

![image](https://user-images.githubusercontent.com/56728301/152236309-388f60e3-3633-4926-bf67-a376866e760b.png)

**Comment by binayaksadangi** [comment]
issue resolved
